Autopay/urls.py
from django.conf.urls import url , include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pay/', include('pay.urls')),
    url(r'^', include('pay.urls')),
]

pay/urls.py
from django.conf.urls import url
from . import views

app_name = 'pay'

urlpatterns = [
    url(r'^logout_user/$', views.logout_user, name = 'logout_user'),
    url(r'^login_user/$', views.login_user, name = 'login_user'),
    url(r'^register/$', views.register, name='register'),
    url(r'^$', views.index, name = 'index'),
    url(r'^bank_detail/$', views.bank_detail, name = 'bank_detail'),
    url(r'^gateway/$', views.gateway, name = 'gateway'),
]

pay/models.py
from django.contrib.auth.models import Permission
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    mobile_number = models.CharField(max_length=10)

class Pay(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    is_yes = models.BooleanField(default=False)

    def __str__(self):
        return self.user

pay/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm

class MyRegistrationForm(forms.ModelForm):
    re_password = forms.CharField(widget = forms.PasswordInput(attrs = {'placeholder':'Confirm your Password','class':'form-control','name':'confirm'}))


    class Meta:
        model = User
        fields = ['first_name','last_name', 'username', 'mobile_number', 'email', 'password']
        widgets = {
                'first_name' : forms.TextInput(attrs = {'placeholder':'Enter your First-Name','type':'text','class':'form-control','name':'first_name','id':'first_name'}),
                'last_name': forms.TextInput(attrs = {'placeholder':'Enter your Last-Name','type':'text','class':'form-control','name':'last_name'}),
                'username': forms.TextInput(attrs = {'placeholder':'Enter your Username','type':'text','class':'form-control','name':'username'}),
                'mobile_number': forms.TextInput(attrs = {'placeholder':'Enter your Mobile Number','type':'text','class':'form-control','name':'mobile_number'}),
                'email': forms.EmailInput(attrs = {'placeholder':'Enter your Email','class':'form-control','name':'email'}),
                'password': forms.PasswordInput(attrs = {'placeholder':'Enter your Password','class':'form-control','name':'password'}),
        }
    def clean_password(self):
        password = self.cleaned_data['password']
        if len(password) < 6:
            raise forms.ValidationError('Password not long enough. Should be >= 6')
        return password

    def clean(self):
        if not self.cleaned_data['password'] == self.cleaned_data['re_password']:
            raise forms.ValidationError("Passwords should match")
        return self.cleaned_data










'''
class MyRegistrationForm(UserCreationForm):
    email = forms.EmailField(required = True,widget=forms.TextInput(attrs={'class' : 'form-control','type':'text','placeholder':'Enter your Email'}))
    first_name = forms.CharField(required = True)
    last_name = forms.CharField(required = True)
    #date_of_birth = forms.DateField(required = True)
    mobile_number = forms.CharField(required = True)


    class Meta:
        model = User
        fields = ('first_name','last_name', 'username', 'mobile_number', 'email', 'password1', 'password2')


    def save(self, commit = True):
        user = super(UserCreationForm, self).save(commit = False)
        user.password = self.cleaned_data['password']
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        #user.date_of_birth = self.cleaned_data['date_of_birth']
        user.mobile_number = self.cleaned_data['mobile_number']

        if commit:
            user.save()

        return user

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
                return password2
        raise forms.ValidationError('Passwords do not match.')
'''
'''
class RegisterForm1(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','email','password','first_name','last_name']

class RegisterForm2(forms.ModelForm):
    dob = forms.DateField()

    class Meta:
        model = UserProfile
        fields = ['phonenumber','dob']
'''

pay/views.py
from django.shortcuts import render , get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from .forms import MyRegistrationForm
from .models import User, Pay
from twilio.rest import TwilioRestClient


# Create your views here.

def logout_user(request):
    logout(request)
    form = MyRegistrationForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'pay/trylogin.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                #albums = Album.objects.filter(user=request.user)
                return render(request, 'pay/index.html')
            else:
                return render(request, 'pay/trylogin.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'pay/trylogin.html', {'error_message': 'Invalid login'})
    return render(request, 'pay/trylogin.html')

def register(request):
    form = MyRegistrationForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username,password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'pay/index.html')
    return render(request, 'pay/tryregister.html',{'form':form})

def index(request):
    if not request.user.is_authenticated():
        return render(request, 'pay/trylogin.html')
    else:
        data = Pay.objects.filter(user=request.user)
        if request.method == "POST":
            check = request.POST['checkbox']
            if check:
                data.is_yes = "True"
            return render(request, 'pay/gateway.html',{'user':user})
        return render(request, 'pay/index.html',{'data':data})

def bank_detail(request):
    if not request.user.is_authenticated():
        return render(request, 'pay/trylogin.html')
    else:
        return render(request, 'pay/bank_detail.html')

def gateway(request):
    if not request.user.is_authenticated():
        return render(request, 'pay/trylogin.html')
    else:

        account_sid = "ACa6d4cb06b269945f34462a435110511f"
        auth_token = "4c74480dcf8daab2fc8a078e5ca40d43"
        client = TwilioRestClient(account_sid, auth_token)

        message = client.messages.create(to="+917610002521", from_="+13176224171",
                                                 body="you have selected autopay next time you can pay automatically via calling to TOLL FREE no. 1800 1234 5678 ")



        return render(request, 'pay/gateway.html')

pay/templates/pay/bank_detail.html
{% extends 'pay/base.html' %} {% block title %}Bank Details{% endblock %} {% block body %}

<div class="panel" id="aboutus" style="width: 900px; height: 700px;">


<div class="panel-heading">Bank-SBI</div>
<div class="panel-body">Account no:4000 1000 0000 0000</div>
<br />
<br />

<div class="panel-heading">Bank-ICICI</div>
<div class="panel-body">Account no:3900 1000 0000</div>

</div>

<div class="panel" id="services">

</div>

<div class="panel" id="gallery">


</div>


</div>
</div>
</div>
{% endblock %}

pay/templates/pay/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>{% block title %}{% endblock %}</title>
{% load staticfiles %}
<meta name="keywords" content="mini social, free download, website templates, CSS, HTML" />
<meta name="description" content="Mini Social is a free website template from templatemo.com" />

<link href="{% static 'pay/templatemo_style.css' %}" rel="stylesheet" type="text/css" />


<link rel="stylesheet" href="{% static 'pay/coda-slider.css' %}" type="text/css" media="screen" charset="utf-8" />

<script src="js/jquery-1.2.6.js" type="text/javascript"></script>
<script src="js/jquery.scrollTo-1.3.3.js" type="text/javascript"></script>
<script src="js/jquery.localscroll-1.2.5.js" type="text/javascript" charset="utf-8"></script>
<script src="js/jquery.serialScroll-1.2.1.js" type="text/javascript" charset="utf-8"></script>
<script src="js/coda-slider.js" type="text/javascript" charset="utf-8"></script>
<script src="js/jquery.easing.1.3.js" type="text/javascript" charset="utf-8"></script>


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
</head>
<body>

<div id="slider">

    <div id="templatemo_sidebar">
    	<div id="templatemo_header" style="padding:inherit">
        	<a href="http://emitra.rajasthan.gov.in/" target="_parent"><img src="{% static 'pay/image/templatemo_logo.png' %}" alt="E-mitra" style="width: 230px; height: 144px;"/></a>
        </div> <!-- end of header -->

        <ul class="navigation" style="padding-top:40px ">
            <li><a href="{% url 'pay:index' %}">PAY BILLS<span class="ui_icon home"></span></a></li>
            <li><a href="{% url 'pay:bank_detail' %}">BANK DETAILS<span class="ui_icon aboutus"></span></a></li>
            <li><a href="#services" >TRANSACTION HISTORY<span class="ui_icon services"></span></a></li>
            <li><a href="#gallery">PROFILE<span class="ui_icon gallery"></span></a></li>
            <li><a href="{% url 'pay:logout_user' %}">Logout<span class="ui_icon gallery"></span></a></li>
        </ul>
    </div> <!-- end of sidebar -->
</div>

{% block body %}
{% endblock %}
        </body>
</html>

pay/templates/pay/base_visitor.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
    {% load staticfiles %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<!-- Website CSS style -->
		<link rel="stylesheet" type="text/css" href="{% static 'pay/logreg.css' %}"/>

		<!-- Website Font style -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


		<!-- Google Fonts -->
		<link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>

	</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'pay:index' %}">Autopay</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'pay:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'pay:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

pay/templates/pay/form_template.html
{% for field in form %}
    <div class="form-group">
        <label class="control-label" >{{ field.label_tag }}<span>*</span></label>
        <div class="input-group">{{ field }}</div>
    </div>
{% endfor %}

pay/templates/pay/gateway.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Gateway</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <div class="jumbotron">
    <h1>Payment Gateway</h1>

</div>
</div>
<a href="{% url 'pay:index' %}">Click here</a> to go to home page.
</body>
</html>

pay/templates/pay/index.html
{% extends 'pay/base.html' %} {% block title %}Pay Bill{% endblock %} {% block body %}
<div id="templatemo_main" style="
  width: 850px;
  padding-top: -;
  padding-bottom: 0px;">


    <div id="content">

        <!-- scroll -->


        <div class="scroll" style="overflow: hidden;width: 1000px;height: 700px;">
            <div class="scrollContainer" style="margin-top:0px">

                <div class="panel" id="home" style="width: 1000px; height: 700px;">
                    <div class="container">
                        <div class="row" style="font-size:15px;padding: 5px;">
                            <div class="col-sm-12">

                            </div>
                            <!-- panel preview -->
                            <div class="col-sm-5">
                                <h4>Pay Bill:</h4>
                                <div class="panel panel-default">
                                    <div class="panel-body form-horizontal payment-form">
                                        <div class="form-group">
                                            <label for="bill_type" class="col-sm-3 control-label">Select Bill</label>
                                            <div class="col-sm-9 style=" padding: 5px; "">
                                                <select class="form-control" id="Select Bill" name="bill_type">
                          <option>--select--</option>
                          <option>Electricity Bill</option>
                          <option>Water Bill</option>
                          <option>Telephone Bill</option>
                          <option>Postpaid Bill</option>
                          <<option>Broadband</option>
                      </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="bill_no" class="col-sm-3 control-label">Enter Bill No.</label>
                                            <div class="col-sm-9">
                                                <input type="text" class="form-control" id="concept" name="concept">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="card" class="col-sm-3 control-label">Payment Mode</label>
                                            <div class="col-sm-9">
                                                <select class="form-control" id="Select Bill" name="bill_type">
                          <option>--select--</option>
                          <option>Debit Card</option>
                          <option>Credit Card</option>

                      </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="card_no" class="col-sm-3 control-label">Card Number</label>
                                            <div class="col-sm-9">
                                                <input type="text" class="form-control" id="description" name="description">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="cvv" class="col-sm-3 control-label">CVV Code</label>
                                            <div class="col-sm-9">
                                                <input type="number" class="form-control" id="amount" name="amount">
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="date" class="col-sm-3 control-label">Date of Expiry</label>
                                            <div class="col-sm-9">
                                                <input type="date" class="form-control" id="date" name="date"><br />
                                                <label><span style="color:red">
                                                  <form class="form-horizontal" role="form" action="{% url 'pay:gateway' %}" method="post" enctype="multipart/form-data">
                                                      {% csrf_token %}
                                                  <input name = "checkbox" type="checkbox" {% if data.is_yes %}checked{% endif %}> Auto-Pay next time</span></label>
                                            </div>
                                        </div><br>
                                        <div class="form-group">

                                            <div class="col-sm-12 text-right">
                                                <button type="submit" class="btn btn-default preview-add-button">
                          <span class="glyphicon glyphicon-plus"></span> Submit
                      </button></form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- / panel preview -->

                        </div>
                    </div>
                </div>
                <!-- end of home -->

                {% endblock %}

pay/templates/pay/trylogin.html
{% extends 'pay/base_visitor.html' %} {% block title %}Log In{% endblock %} {% block login_active %}active{% endblock %} {% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-lg-8 col-md-8"></div>
        <div class="col-lg-4 col-md-4" style="margin-bottom:20px;">
            <!--<div class="panel panel-default">-->
                <div class="panel-heading">
                    <div class="panel-title text-center">
                        <h1 class="title">E-MITRA</h1>

                    </div>
                </div>
                <div class="main-login main-center" style="margin-bottom:40px;">
                    {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'pay:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label" for="id_username">
                                Username/Mobile Number
                            </label>
                            <div class="input-group">
                              <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                                <input class="form-control" id="id_username" maxlength="30" name="username" type="text" placeholder="Enter Username/Mobile Number">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="id_password">
                                Password
                            </label>
                            <div class="input-group">
                              <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                                <input id="id_password" class="form-control" maxlength="30" name="password" type="password" placeholder="Enter Password">
                            </div>
                            <div class="well-sm" style="text-align:left; padding:3px"><small><a href="#">Forgot Password</a></small></div>
                        </div>
                        <div class="form-group">

                                <button type="submit" class="btn btn-primary btn-lg btn-block login-button">Login</button>

                        </div>
                    </form>
                    <div class="form-group">
                        <div class="well-sm" style="text-align:center;font-size:18px; padding:3px"><small>OR</small></div>
                        <a href="{% url 'pay:register' %}">
                            <button type="button" class="btn btn-primary btn-lg btn-block login-button">Register</button>
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </div>

<!--</div>-->

{% endblock %}

pay/templates/pay/tryregister.html
{% extends 'pay/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}}

{% block body %}
<div class="container-fluid">

    <div class="row">
      <div class="col-lg-8 col-md-8"></div>
        <div class="col-lg-4 col-md-4" style="margin-bottom:20px;">
            <!--<div class="panel panel-default">-->
              <div class="panel-heading">
                  <div class="panel-title text-center">
                      <h1 class="title">E-MITRA</h1>
                      <hr />
                  </div>
              </div>
                <div class="main-login main-center" style="margin-bottom:40px;">

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <!--{% include 'pay/form_template.html' %}-->
                        <div class="form-group">
                            <label for="first_name" class="control-label" >First Name<span>*</span></label>
                            <div class="input-group">
                              <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                              {{ form.first_name }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="first_name" class="control-label" >Last Name <span>*</span></label>
                            <div class="input-group">
                              <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                              {{ form.last_name }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="first_name" class="control-label" >Username <span>*</span></label>
                            <div class="input-group">
                              <span class="input-group-addon"><i class="fa fa-users fa" aria-hidden="true"></i></span>
                              {{ form.username }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="first_name" class="control-label" >Mobile Number<span>*</span></label>
                            <div class="input-group">
                              <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                              {{ form.mobile_number }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="first_name" class="control-label" >Email<span>*</span></label>
                            <div class="input-group">
                              <span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
                              {{ form.email }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="first_name" class="control-label" >Password<span>*</span></label>
                            <div class="input-group">
                              <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                              {{ form.password }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="first_name" class="control-label" >Confirm Password<span>*</span></label>
                            <div class="input-group">
                              <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                              {{ form.re_password }}
                            </div>
                        </div>
                        <div class="well-sm" style="text-align:left; padding:3px"><small><span style="color:red">Fields Marked With * are mendatory</span></small></div>
                        <div class="form-group">

                                <button type="submit" class="btn btn-primary btn-lg btn-block login-button">Register</button>

                        </div>

                    </form>
                    <div class="login-register">
                        <a href="{% url 'pay:login_user' %}">Login</a>
                    </div>
                </div>

            </div>
        </div>
    </div>

<!--</div>-->

{% endblock %}